version: '3.6'
services:
  picatrix:
    image: us-docker.pkg.dev/osdfir-registry/picatrix/picatrix:latest
    ports:
      - 8899:8899
    restart: on-failure
    volumes:
      - ../:/usr/local/src/picatrix/:ro
      - /tmp/:/usr/local/src/picadata/

